title:              AKS Engineering Team Blog
email:              brian.redmond@microsoft.com
description:        Insights and best practices from the AKS Engineering Team
author:             Brian Redmond
baseurl:            "/AKS"
url:                ""

remote_theme:       StartBootstrap/startbootstrap-clean-blog-jekyll

# Social Profiles
twitter_username:   theakscommunity
github_username:    Azure/aks
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
